-----dia 01/03/13 TABLE DE FUNCIONARIO  SEM CHAVE PRIMARIA
----
CREATE TABLE FUNCIONARIO (
REGISTRO NUMBER (7),
NOMEFUNC VARCHAR2 (80),
ENDERFUNC VARCHAR2 (80) ,
SALARIO NUMBER (7,2));
  ---- INSERT DADOS NA TABLE FUNCIONARIO  ---

INSERT INTO FUNCIONARIO VALUES
   (200,'JOÃO','R.QUATA,20',2500.00);
INSERT INTO FUNCIONARIO VALUES
    (201,'MARIA','R.AMADOR BUENO,333',3000.00);

           --VER OS DADOS  ---
SELECT * FROM FUNCIONARIO
  ----ELIMINAR TABELA
DROP TABLE FUNCIONARIO;
-----CRIAR TABELACOM CHAVE PRIMARIA ---
CREATE TABLE FUNCIONARIO (
REGISTRO NUMBER (7),
NOMEFUNC VARCHAR2 (80),
ENDERFUNC VARCHAR2 (80) ,
SALARIO NUMBER (7,2),
CONSTRAINTS FUNC_PK PRIMARY KEY (REGISTRO)) ;

INSERT INTO VALUES (200,'JOÃO','R.QUATA,20',2500.00);
INSERT INTO FUNCIONARIO VALUES
    (201,'MARIA','R.AMADOR BUENO,333',3000.00);

 SELECT * FROM FUNCIONARIO
 ---CRIAR TABELA DE DEPENDENTES
 CREATE TABLE DEPENDETE (
 IDDEP NUMBER (4),
 NOMEDEP VARCHAR (50) ,
 DTNASC DATE ,
 REGISTRO NUMBER (7) ,
CONSTRAINTS DEP_PK PRIMARY KEY (IDDEP),
CONSTRAINTS DEP_FK FOREIGN KEY (REGISTRO) REFERENCES
FUNCIONARIO (REGISTRO));

INSERT INTO DEPENDETE VALUES (1,'PEDRO HENRIQUE', '03/04/2008',201);
INSERT INTO DEPENDETE VALUES (2, 'GUILHERME','07/07/2002',202 );
---AQUI DA ERRO POR 202 NÃO TEM FUNCIONARIO ---
INSERT INTO DEPENDETE VALUES (3,'FATIMA','12/12/2012',201 );
INSERT INTO DEPENDETE VALUES (4,'ANA MARIA','10/10/2007',201);

 SELECT* FROM DEPENDETE;
 SELECT NOMEDEP FROM DEPENDETE;
 SELECT  IDDEP,NOMEDEP FROM DEPENDETE WHERE IDDEP=3;